### ISSUE TITLE
prefix req.baseUrl in createPackageURL redirects

### ISSUE THREAD

**Issue by tarun** [unpkg/npm-http-server#50]
`/baseUrl/package@latest` gets redirected to `/package@version` instead of `/baseUrl/package@version`

when mounting handler on a baseUrl `app.use('/npm-assets', createRequestHandler())`
`parsePackageURL` works fine as `req.url` does not include the baseUrl

However the redirected url does not have the `baseUrl` prefixed - resulting in 404s, etc.

**Comment by mjackson** [comment]
Fixed in #51
