### ISSUE TITLE
ETag or Last-Modified header

### ISSUE THREAD

**Issue by jdalton** [unpkg/npm-http-server#54]
Google PageSpeed Insights is recommending etag for [cache validation](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#validating-cached-responses-with-etags). I'm not super in the know on all this stuff but wanted to pass it along. The notice was that the resources are missing a cache validator.

> Resources that do not specify a cache validator cannot be refreshed efficiently. Specify a Last-Modified or ETag header to enable cache validation.

<table>
<tr>
<th>
jsdelivr
</th>
</tr>
<tr>
<td>
<pre>
access-control-allow-origin:*
cache-control:public, max-age=31536000
content-encoding:gzip
content-type:application/javascript; charset=utf-8
date:Sun, 23 Oct 2016 00:11:14 GMT
etag:W/"57f5bf37-11849"
last-modified:Thu, 06 Oct 2016 03:04:23 GMT
server:NetDNA-cache/2.2
status:200
timing-allow-origin:*
vary:Accept-Encoding
x-cache:HIT
</pre>
</td>
</tr>
</table>

<table>
<tr>
<th>
unpkg
</th>
</tr>
<tr>
<td>
<pre>
access-control-allow-origin:*
cache-control:public, max-age=31536000
cf-cache-status:HIT
cf-ray:2f60f87a1d592a13-SEA
content-encoding:gzip
content-type:application/javascript
date:Sun, 23 Oct 2016 00:11:14 GMT
expires:Mon, 23 Oct 2017 00:11:14 GMT
server:cloudflare-nginx
status:200
strict-transport-security:max-age=15552000; includeSubDomains; preload
vary:Accept-Encoding
via:1.1 vegur
x-content-type-options:nosniff
</pre>
</td>
</tr>
</table>

**Comment by mjackson** [comment]
Thanks for the heads up, @jdalton. I'm pushing out a fix right now to unpkg.com that will include `ETag` headers.

**Comment by jdalton** [comment]
Thank you!

**Comment by papandreou** [comment]
@mjackson, you also need to support the `If-None-Match` request header for the `ETag` header to provide any value. When the client lists the current `ETag` header value in `If-None-Match`, you should reply with a 304 Not Modified.

See https://tools.ietf.org/html/rfc7232#section-3.2

**Comment by mjackson** [comment]
Thanks for the reminder, @papandreou!

Currently, Cloudflare takes care of returning a 304 on unpkg.com to clients that specify `If-None-Match`. You can see this in the following cURL session:

```
$ curl https://unpkg.com/react@15.3.2/dist/react.min.js -v -H 'If-None-Match: W/"24545-1574387ece0"'
> GET /react@15.3.2/dist/react.min.js HTTP/1.1
> Host: unpkg.com
> User-Agent: curl/7.49.1
> Accept: */*
> If-None-Match: W/"24545-1574387ece0"
> 
< HTTP/1.1 304 Not Modified
< Date: Thu, 03 Nov 2016 23:02:05 GMT
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Cache-Control: public, max-age=31536000
< Etag: W/"24545-1574387ece0"
< Via: 1.1 vegur
< CF-Cache-Status: HIT
< Expires: Fri, 03 Nov 2017 23:02:05 GMT
< Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
< X-Content-Type-Options: nosniff
< Server: cloudflare-nginx
< CF-RAY: 2fc373a96e585426-LAX
```

Only when you hit the origin server (i.e. https://unpkg.herokuapp.com) do you see a 200:

```
$ curl https://unpkg.herokuapp.com/react@15.3.2/dist/react.min.js -v -H 'If-None-Match: W/"24545-1574387ece0"'
> GET /react@15.3.2/dist/react.min.js HTTP/1.1
> Host: unpkg.herokuapp.com
> User-Agent: curl/7.49.1
> Accept: */*
> If-None-Match: W/"24545-1574387ece0"
> 
< HTTP/1.1 200 OK
< Server: Cowboy
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Content-Type: application/javascript
< Content-Length: 148805
< Cache-Control: public, max-age=31536000
< Etag: W/"24545-1574387ece0"
< Date: Thu, 03 Nov 2016 23:01:50 GMT
< Via: 1.1 vegur
```

Of course, since I maintain `npm-http-server` as a separate package, I should probably include support for `If-None-Match` here. But my main motivation in doing this work was to get support for ETag on unpkg.com, which I have.

If you'd like to make a PR to this package, I'll happily merge :)
