### ISSUE TITLE
Empty file returned for a package (graphiql@0.7.8)

### ISSUE THREAD

**Issue by orls** [unpkg/npm-http-server#56]
(Apologies in advance if this isn't the right forum for reporting such issues – I'm _guessing_ the root issue is in this codebase, but not sure)

I've successfully loaded [graphiql@0.7.8 minified](https://unpkg.com/graphiql@0.7.8/graphiql.min.js) in the past; I even have a cached version in my browser. But other devs working with me can't load it. 

It would have vanished some time in the last week or so I think (hard to pin down; my browser shows a cache max-age of over a month)

It's returning 200 with 0 content-length; if there is some unavoidable reason it can't be served, then a 4**/5** error code might make sense in these cases

**Comment by mjackson** [comment]
Sorry, I'm a little late here but I can't see the issue you're describing. It may have been a temporary hiccup in the service. Here's what I see right now:

```
$ curl -v https://unpkg.com/graphiql@0.7.8/graphiql.min.js > /dev/null
> GET /graphiql@0.7.8/graphiql.min.js HTTP/1.1
> Host: unpkg.com
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 10 Dec 2016 15:41:34 GMT
< Content-Type: application/javascript
< Content-Length: 511679
< Connection: keep-alive
< Set-Cookie: __cfduid=da113300f3b832d9853999c42eb67e6a41481384494; expires=Sun, 10-Dec-17 15:41:34 GMT; path=/; domain=.unpkg.com; HttpOnly
< Access-Control-Allow-Origin: *
< Cache-Control: public, max-age=31536000
< Etag: W/"7cebf-156d35a2eb0"
< Via: 1.1 vegur
< CF-Cache-Status: HIT
< Expires: Sun, 10 Dec 2017 15:41:34 GMT
< Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
< X-Content-Type-Options: nosniff
< Server: cloudflare-nginx
< CF-RAY: 30f1cd431d270d37-LAX
```

**Comment by orls** [comment]
Hm, I'm still seeing this issue from where I am (London, UK):

```$ curl -v https://unpkg.com/graphiql@0.7.8/graphiql.min.js > /dev/null
curl -v https://unpkg.com/graphiql@0.7.8/graphiql.min.js > /dev/null
> GET /graphiql@0.7.8/graphiql.min.js HTTP/1.1
> Host: unpkg.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 11 Dec 2016 22:51:56 GMT
< Content-Type: application/javascript
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: __cfduid=d8ddd0112fad123084df8c0a473969ed41481496716; expires=Mon, 11-Dec-17 22:51:56 GMT; path=/; domain=.unpkg.com; HttpOnly
< Access-Control-Allow-Origin: *
< Cache-Control: public, max-age=31536000
< Etag: W/"0-1582be20464"
< Via: 1.1 vegur
< CF-Cache-Status: HIT
< Expires: Mon, 11 Dec 2017 22:51:56 GMT
< Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
< X-Content-Type-Options: nosniff
< Server: cloudflare-nginx
< CF-RAY: 30fc810bda963536-LHR
```

Note the `Content-length: 0`. Looks like the 0-byte file has got stuck in _some_ cloudflare regional edge cache. Short-term, You might want to consider purging the cache, and tweaking how aggressive/long-lived cloudflare's caching is.

Longer term: A 0-byte file with a 200 response means either that your code returned that at some point/under some conditions (and it then got stuck in cache) – or that cloudflare have some kind of bug.

FWIW, everything else I've ever got off unpkg is fine (thanks for the work!), and this file _was_ at one point fine, so it's far from common.

**Comment by mjackson** [comment]
> Short-term, You might want to consider purging the cache, and tweaking how aggressive/long-lived cloudflare's caching is.

👍 I'll initiate a purge of the cache right now. Weekends are a good time to do it when traffic is low.

**Comment by orls** [comment]
Thanks - it's working form here now :)

**Comment by whipermr5** [comment]
Just for the record, I found another instance of the original issue: https://github.com/postgraphql/postgraphql/issues/249
