### ISSUE TITLE
Smartly figure out minified version of given package

### ISSUE THREAD

**Issue by truongsinh** [unpkg/npm-http-server#57]
Hi,

I use `react` for my project, and would love to use `system-csp-production.js` to load library from unpkg (like this https://github.com/unpkg/unpkg.com/issues/16). It would be ideal that we have a universal way to serve minified version of any given package, like
- `https://unpkg.com/react@15.3.1` resolved to `https://unpkg.com/react@15.3.1/dist/react.min.js`

Basically, we will have to smartly guest the minified file of given package, like:
- inside `build`, `dist`, `umd` dir
- ends with `.min.js`, OR not end with `.src.js`

I'm happy to make MR

**Comment by mjackson** [comment]
I don't want to make the system too "smart" since we cache stuff so heavily. Instead, I'd prefer we be as explicit as possible. However, you may be interested in #59 which proposes adding another field to `package.json` so you can have more control over the bare URL.
