### ISSUE TITLE
CORS Redirects (Chrome)

### ISSUE THREAD

**Issue by streamich** [unpkg/npm-http-server#63]
When not specifying the exact package version like this:

    https://unpkg.com/react/dist/react.min.js

It redirects to the `latest` version:

    https://unpkg.com/react@15.4.1/dist/react.min.js

However, the redirects are not followed from Chrome using *synchronous* `xhr` requests. In Firefox they work fine.

[Here is JSFiddle example](https://jsfiddle.net/9hj4ghxr/1/).

Maybe add additional API, for example, to list all known versions, like this:

```
GET https://unpkg.com/react?versions

...
15.4.0
15.4.1
```

That way, if the exact version is not known, one could lookup the available versions first.

Alternatively, when `latest` version is specified, it could return the contents, instead of redirecting.

    https://unpkg.com/react@latest

But then it's more tricky with CDN caching.

**Comment by mjackson** [comment]
This is [an old Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=68105). It doesn't look like they're very interested in solving it. It doesn't feel like sync XHR is worth the effort, honestly.

**Comment by streamich** [comment]
I am writing a browser `require` function that uses unpkg.com as cdn. The problem is that if user wants to load a module *synchronously* and does not specify an exact version, it is not possible to do anything even to just load the latest version because Chrome would not redirect.

I need to resolve to *asynchronous* XHR to fake the synchronous loading by `throw`ing if a module is not available, downloading it asynchronously, trying to recompile the module again, and repeating the process if necessary until all deps are loaded in kinda asynchronous-synchronous way.

**Comment by mjackson** [comment]
You're asking me to add API so you can work around a browser-specific bug that the vendor doesn't intend to fix because sync XHR is always a bad idea. I'm sorry, but that just doesn't seem like a good use of my time and effort.

**Comment by streamich** [comment]
Synchronous XHR may be a bad idea, but 99% of npm modules use sync loading (because of Node.js), i.e. `var React = require('react');` instead of `require(['react'], (React) => { ... });`.

Which can be loaded perfectly fine using synchronous module loading with XHR.

Another way to think about it: 99% of stuff currently hosted on unpkg.com (and I love the service) is unusable because modules usually uses sync `require` and you cannot load all of that using async XHR and due to Chrome's bug.

All that is needed is a very simple `GET` request that returns the *latest* version:

```
GET https://unpkg.com/react?latest

"15.4.1"
```

**Comment by streamich** [comment]
I am not familiar with the code base, but as far as I see you just need to insert this `if else` branch somewhere [here](https://github.com/unpkg/npm-http-server/blob/master/modules/index.js#L252-L254):

```js
else if(query.versions != null) {
  getPackageInfo(registryURL, packageName, (error, packageInfo) => {
    const {versions} = packageInfo
    sendJSON(res, versions, OneMinute)
  })
}
```

**Comment by mjackson** [comment]
Have you seen https://github.com/unpkg/unpkg.com/issues/16 ? Would you be interested in helping with that effort? The SystemJS people seem to have worked quite extensively on this problem, and I'd love to support what they're doing.

**Comment by streamich** [comment]
With regards to #16, they want you to treat `./umd` and `./dist` folders as root folder when `as=umd` is specified.

I would rather go for a more generic way of listing the root folders explicity `root=umd,dist` that way you
know without any "magic" which folders you should try as roots.

But it does not really relate to this issue, because SystemJS needs UMD modules to work, so they need packages to explicitly build UMD versions for them as far as I understand, which most packages don't do.

That's fine for performance and packages specifically built for the web, but on npm 99% of the packages are written for Node.js and they use synchronous CommonJS loading, which SystemJS says explicitly they [are not really interested in](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#commonjs):

> Note that CommonJS modules on npm, loaded as CommonJS may well not load correctly through SystemJS. This is because SystemJS does not implement the NodeJS loading algorithm.

And what I am doing is exactly implementing the *NodeJS loading algorigth*, for me it does not matter if it is synchronous or asynchronous, more important currently is to unlock all the CommonJS modules written for Node.js and make them available in the browser.
